//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPaymentPlan
    {
        public int PaymentPlanID { get; set; }
        public string Division_ID { get; set; }
        public string Account { get; set; }
        public Nullable<System.DateTime> PaymentPlanDate { get; set; }
        public Nullable<int> PaymentPlanStatusID { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<decimal> LastPaymentAmount { get; set; }
        public Nullable<System.DateTime> FirstPaymentDate { get; set; }
        public Nullable<decimal> FirstPaymentAmount { get; set; }
        public Nullable<int> CycleDay { get; set; }
        public Nullable<int> Terms { get; set; }
        public string Responsibility { get; set; }
        public string Portfolio { get; set; }
        public Nullable<int> StartingPayments { get; set; }
        public Nullable<decimal> StartingPaymentAmount { get; set; }
        public Nullable<decimal> AccountBalance { get; set; }
        public decimal PaymentPlanAmount { get; set; }
    }
}
