//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountActivity
    {
        public int AccountActivityID { get; set; }
        public string Division_ID { get; set; }
        public string Account { get; set; }
        public string UserID { get; set; }
        public Nullable<long> Activity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual RACCOUNT RACCOUNT { get; set; }
    }
}
