//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaCodesByTimeZone
    {
        public int AreaCode { get; set; }
        public string AreaCodeName { get; set; }
        public string State { get; set; }
        public string ZoneName { get; set; }
    }
}
