//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchType
    {
        public BatchType()
        {
            this.Batches = new HashSet<Batch>();
        }
    
        public int BatchTypeID { get; set; }
        public string Batch_Type { get; set; }
        public string Begin_seq { get; set; }
        public string End_seq { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
    }
}
