//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBA
    {
        public string Account { get; set; }
        public string Score { get; set; }
        public string OwnHome { get; set; }
        public string AcctsOpenedLast6mths { get; set; }
        public string InquiriesLast6mths { get; set; }
        public string DerogatoryAccts { get; set; }
        public string PaidLast6mths { get; set; }
        public Nullable<decimal> MortgageHighCredit { get; set; }
        public Nullable<decimal> MortgageBalance { get; set; }
        public Nullable<decimal> SecondMortgageHighCredit { get; set; }
        public Nullable<decimal> SecondMortgageBalance { get; set; }
        public Nullable<decimal> RevolvingHighCredit { get; set; }
        public Nullable<decimal> RevolvingBalance { get; set; }
        public Nullable<decimal> AvailableRevolving { get; set; }
        public Nullable<decimal> AvailableBankCard { get; set; }
        public Nullable<decimal> AutoBalance { get; set; }
        public string PercentAutoUsed { get; set; }
        public Nullable<decimal> AutoLeaseBalance { get; set; }
        public string PercentLeaseUsed { get; set; }
        public string Division_ID { get; set; }
        public string Score2 { get; set; }
        public Nullable<System.DateTime> DateLoaded { get; set; }
        public string BKStatus { get; set; }
        public string Deceased { get; set; }
    
        public virtual RACCOUNT RACCOUNT { get; set; }
    }
}
