//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBRAccountStatu
    {
        public int CBRAccountStatusID { get; set; }
        public string CBRAccountStatus { get; set; }
        public string CBRAccountStatusDesc { get; set; }
    }
}
