//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.RACCOUNTs = new HashSet<RACCOUNT>();
        }
    
        public int ClientID { get; set; }
        public Nullable<int> SalesRepID { get; set; }
        public Nullable<int> CustomerServiceRepID { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> ClientTypeID { get; set; }
        public string BillingCompany { get; set; }
        public string BillingContact { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingPhone { get; set; }
        public string BillingFax { get; set; }
        public string BillingEmail { get; set; }
        public Nullable<int> BillingTypeID { get; set; }
        public Nullable<int> BillingOptionID { get; set; }
        public Nullable<int> Terms { get; set; }
        public Nullable<double> FinanceCharge { get; set; }
        public Nullable<int> InvoiceSchedule { get; set; }
        public Nullable<int> InvoiceoptionID { get; set; }
        public Nullable<int> InvoiceTemplateID { get; set; }
        public Nullable<bool> InvoiceDetail { get; set; }
        public string BillingNotes { get; set; }
        public string CustomerServiceContact { get; set; }
        public string CustomerServiceAddress1 { get; set; }
        public string CustomerServiceAddress2 { get; set; }
        public string CustomerServiceCity { get; set; }
        public string CustomerServiceState { get; set; }
        public string CustomerServiceZip { get; set; }
        public string CustomerServicePhone { get; set; }
        public string CustomerServiceFax { get; set; }
        public string ReportEmails { get; set; }
        public Nullable<int> ReportOptionID { get; set; }
        public string CustomerServiceNotes { get; set; }
        public string httpURL { get; set; }
        public string ftpURL { get; set; }
        public string ftpUserName { get; set; }
        public string ftpPassword { get; set; }
        public string ftpFolder { get; set; }
        public string ClientPassword { get; set; }
        public Nullable<int> LateFeeTerms { get; set; }
        public Nullable<decimal> LateFee { get; set; }
    
        public virtual ICollection<RACCOUNT> RACCOUNTs { get; set; }
    }
}
