//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtorsVehicle
    {
        public string Division_ID { get; set; }
        public string Account { get; set; }
        public string VehicleYear { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleYearMakeModel { get; set; }
        public string VehicleMiles { get; set; }
        public string VehicleVIN { get; set; }
        public string VehicleBookValue { get; set; }
        public string VehicleCondition { get; set; }
        public string VehicleTag { get; set; }
        public string VehicleColor { get; set; }
        public Nullable<int> VehicleOwnerTypeID { get; set; }
        public Nullable<int> DamageTypeID { get; set; }
        public string DamageAmount { get; set; }
        public string NameOnTitle { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Update_ID { get; set; }
        public string Update_Type { get; set; }
        public string PaymentAmount { get; set; }
        public string DownPayment { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> LoanTerms { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string SaleAmount { get; set; }
        public string RepoStatus { get; set; }
        public string RepoAgent { get; set; }
        public string RepoAgentAddress1 { get; set; }
        public string RepoAgentAddress2 { get; set; }
        public string RepoAgentCity { get; set; }
        public string RepoAgentState { get; set; }
        public string RepoAgentZip { get; set; }
        public string RepoAgentPhone { get; set; }
        public string RepoAgentFax { get; set; }
        public string RepoAgentEmail { get; set; }
        public Nullable<System.DateTime> RepoDate { get; set; }
        public string RepoFee { get; set; }
        public string AuctionName { get; set; }
        public Nullable<System.DateTime> AuctionDate { get; set; }
        public string AuctionAmount { get; set; }
        public string AuctionFee { get; set; }
        public string ReconditioningFee { get; set; }
        public string TransportationFee { get; set; }
        public Nullable<System.DateTime> RedemptionExpirationDate { get; set; }
    
        public virtual RACCOUNT RACCOUNT { get; set; }
    }
}
