//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentLibraryCategory
    {
        public DocumentLibraryCategory()
        {
            this.TemplateLibraries = new HashSet<TemplateLibrary>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDesc { get; set; }
        public bool Media { get; set; }
    
        public virtual ICollection<TemplateLibrary> TemplateLibraries { get; set; }
    }
}
