//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastCallResult
    {
        public string Division_ID { get; set; }
        public string Account { get; set; }
        public string Last_Call_Result_Home { get; set; }
        public string Last_Call_Result_Work { get; set; }
        public string Last_Call_Result_Cell { get; set; }
        public string Last_Call_Result_Other { get; set; }
        public string Last_Call_Number_Home { get; set; }
        public string Last_Call_Number_Work { get; set; }
        public string Last_Call_Number_Cell { get; set; }
        public string Last_Call_Number_Other { get; set; }
        public Nullable<System.DateTime> Last_Call_Date_Home { get; set; }
        public Nullable<System.DateTime> Last_Call_Date_Work { get; set; }
        public Nullable<System.DateTime> Last_Call_Date_Cell { get; set; }
        public Nullable<System.DateTime> Last_Call_Date_Other { get; set; }
        public string Last_Call_Time_Home { get; set; }
        public string Last_Call_Time_Work { get; set; }
        public string Last_Call_Time_Cell { get; set; }
        public string Last_Call_Time_Other { get; set; }
    
        public virtual RACCOUNT RACCOUNT { get; set; }
    }
}
