//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCOACode
    {
        public int NCOAID { get; set; }
        public string NCOACode1 { get; set; }
        public string NCOADescription { get; set; }
        public Nullable<bool> UpdateAccount { get; set; }
        public string NewStatus { get; set; }
        public string BadAddressFlag { get; set; }
    }
}
