//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioStatusCrossRef
    {
        public int CrossRefID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string Product_Code { get; set; }
        public string Status { get; set; }
        public string ReturnStatus { get; set; }
    
        public virtual RPRODCDE RPRODCDE { get; set; }
        public virtual RSTATU RSTATU { get; set; }
    }
}
