//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recallmaster
    {
        public string Agency { get; set; }
        public string ACCOUNT { get; set; }
        public string OriginalAccount { get; set; }
        public Nullable<System.DateTime> Recall { get; set; }
        public string Portfolio { get; set; }
        public Nullable<decimal> Principal { get; set; }
    }
}
