//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentType
    {
        public int SegmentTypeID { get; set; }
        public string SegmentType1 { get; set; }
        public string SegmentTypeDescription { get; set; }
        public string SegmentWhereClause { get; set; }
        public string SegmentQuery { get; set; }
        public Nullable<int> SegmentOrder { get; set; }
    }
}
