//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public string Division_ID { get; set; }
        public string Account { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public Nullable<double> Distance { get; set; }
        public string TimeZone { get; set; }
        public string Zip { get; set; }
        public string ZipValidation { get; set; }
        public string SSN3 { get; set; }
        public string SSNValidation { get; set; }
        public string AreaCode { get; set; }
        public string HomePhone { get; set; }
        public string HomePhoneValidation { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneValidation { get; set; }
        public string Language { get; set; }
        public Nullable<decimal> AverageHomeValue { get; set; }
        public Nullable<decimal> AverageIncome { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> EmploymentTypeID { get; set; }
        public Nullable<int> HomeOwner { get; set; }
        public Nullable<decimal> CTC { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> NewBalance { get; set; }
        public Nullable<decimal> MonthlyPayment { get; set; }
        public Nullable<double> IRR { get; set; }
        public string Segment1 { get; set; }
        public string Issuer { get; set; }
        public Nullable<int> StatuteOpen { get; set; }
        public Nullable<int> StatuteWritten { get; set; }
        public Nullable<decimal> Liq { get; set; }
        public Nullable<int> Statute { get; set; }
        public string StatuteType { get; set; }
    }
}
