//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettlementRequest
    {
        public int RequestID { get; set; }
        public string Account { get; set; }
        public string Collector { get; set; }
        public Nullable<decimal> Offer { get; set; }
        public Nullable<double> OfferPercent { get; set; }
        public Nullable<System.DateTime> OfferExpireDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public string Portfolio { get; set; }
        public Nullable<System.DateTime> GracePeriodDate { get; set; }
    }
}
