//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statute
    {
        public string State { get; set; }
        public Nullable<int> Statute1 { get; set; }
        public string StateName { get; set; }
        public int StatuteID { get; set; }
        public int StatuteTypeID { get; set; }
        public string Prefer { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ExpectedLiquidation { get; set; }
        public string StateConditional { get; set; }
    
        public virtual StatuteType StatuteType { get; set; }
    }
}
