//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatuteType
    {
        public StatuteType()
        {
            this.Statutes = new HashSet<Statute>();
        }
    
        public int StatuteTypeID { get; set; }
        public string StatuteType1 { get; set; }
    
        public virtual ICollection<Statute> Statutes { get; set; }
    }
}
