//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubIndustry
    {
        public int lngSubIndustryID { get; set; }
        public Nullable<int> lngIndustryID { get; set; }
        public string ShortDescription { get; set; }
        public string Code { get; set; }
        public string SOLType { get; set; }
        public string memLongDescription { get; set; }
    }
}
