//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sup_UploadRecalls
    {
        public string PIMSAcct_ { get; set; }
        public string NewStatus { get; set; }
        public string NewResp { get; set; }
        public Nullable<System.DateTime> Uploaded__y_n_ { get; set; }
    }
}
