//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Expense
    {
        public int Id { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public string ExpenseDescription { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Tbl_Categories Tbl_Categories { get; set; }
    }
}
