//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateLibrary
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public string ItemLink { get; set; }
        public string Activated { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual DocumentLibraryCategory DocumentLibraryCategory { get; set; }
    }
}
