//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZone
    {
        public int TimeZoneID { get; set; }
        public string ZoneName { get; set; }
        public System.DateTime Start1 { get; set; }
        public System.DateTime Stop1 { get; set; }
        public System.DateTime Start2 { get; set; }
        public System.DateTime Stop2 { get; set; }
        public int Offset { get; set; }
    }
}
