//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorType
    {
        public VendorType()
        {
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int VendorTypeID { get; set; }
        public string VendorType1 { get; set; }
    
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
