//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorProduct
    {
        public int VendorProductID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string VendorProduct1 { get; set; }
        public Nullable<decimal> PerHitCost { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
