//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.VendorProducts = new HashSet<VendorProduct>();
        }
    
        public int VendorID { get; set; }
        public string Vendor1 { get; set; }
        public Nullable<int> VendorTypeID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string HTTPURL { get; set; }
        public string FTPURL { get; set; }
        public string FTPUser { get; set; }
        public string FTPPassword { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Email { get; set; }
        public string dtsJob { get; set; }
        public string importJob { get; set; }
        public string exportJob { get; set; }
        public Nullable<bool> import { get; set; }
        public Nullable<bool> ExportToFTP { get; set; }
        public string FTPFolder { get; set; }
        public bool Secured { get; set; }
    
        public virtual ICollection<VendorProduct> VendorProducts { get; set; }
        public virtual VendorType VendorType { get; set; }
    }
}
