//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCoDebtor
    {
        public string DIVISION_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string CoName { get; set; }
        public string CoAddress1 { get; set; }
        public string CoAddress2 { get; set; }
        public string CoCity { get; set; }
        public string CoState { get; set; }
        public string CoZip { get; set; }
        public string CoCounty { get; set; }
        public string CoCountry { get; set; }
        public string CoSSN { get; set; }
        public string CoHomePhone { get; set; }
        public string CoWorkPhone { get; set; }
        public string CoCellPhone { get; set; }
        public string CoOtherPhone { get; set; }
        public string CoDL { get; set; }
        public string CoDLState { get; set; }
        public string CoTimeZone { get; set; }
        public string CoComment { get; set; }
        public Nullable<System.DateTime> CoDOB { get; set; }
        public Nullable<System.DateTime> CoDOD { get; set; }
        public Nullable<System.DateTime> CoAddressUpdateDate { get; set; }
        public string ECOA_COS { get; set; }
    }
}
