//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDebtor
    {
        public string DIVISION_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string COUNTY { get; set; }
        public string COUNTRY { get; set; }
        public string SS_NO { get; set; }
        public string PHONE_HOME { get; set; }
        public string PHONE_WORK { get; set; }
        public string PHONE_OTHER { get; set; }
        public string PHONE_CELL { get; set; }
        public string WorkExt { get; set; }
        public string Email { get; set; }
        public string DL { get; set; }
        public string DLState { get; set; }
        public string TIME_ZONE { get; set; }
        public string DebtorComment { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOD { get; set; }
        public Nullable<System.DateTime> AddressUpdateDate { get; set; }
        public string FuneralHome { get; set; }
        public string CityOD { get; set; }
        public string CountyOD { get; set; }
        public string StateOD { get; set; }
        public string ContactName { get; set; }
        public string ContactTelephone { get; set; }
        public string ECOA { get; set; }
        public string SALUTATION { get; set; }
        public string PREFIX { get; set; }
        public string SUFFIX { get; set; }
        public string GENDER { get; set; }
        public string MIDDLENAME { get; set; }
    }
}
