//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlow
    {
        public int WorkFlowID { get; set; }
        public string WorkFlow1 { get; set; }
        public string WorkFlowSQL { get; set; }
        public Nullable<int> WorkFlowType { get; set; }
        public string WorkFlowTypeValue { get; set; }
        public string WhereClause { get; set; }
        public string FieldList { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> AutoRun { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> LastDateProcessed { get; set; }
        public Nullable<int> NextWorkFlowID { get; set; }
        public string SQLStatement { get; set; }
        public string FromClause { get; set; }
        public string SelectClause { get; set; }
    
        public virtual WorkFlowType WorkFlowType1 { get; set; }
    }
}
